deadlines:
  '3':
    Wed:
      date: 2025/09/17 12:00pm 
      content: ip1
  '4':
    Wed:
      date: 2025/09/24 12:00pm 
      content: tp1
  '6':
    Wed:
      date: 2025/10/08 12:00pm
      content: tp2
  '7':
    Wed:
      date: 2025/10/15 12:00pm
      content: ip2
  '8':
    Wed:
      date: 2025/10/22 12:00pm
      content: tp3
  '13':
    Wed:
      date: 2025/11/25 12:00pm
      content: tp4
  '15':
    Wed:
      date: 2025/12/08 12:00pm
      content: tp5
dates:
  firstMonday: 2025/09/03
  numWeeks: 15
types:
  default:
    className: lesson
  holiday:
    className: holiday